create table if not exists public.resources (
  id text primary key,
  name text not null,
  url text not null unique,
  category text not null,
  summary text not null,
  zone text not null default 'Venezuela',
  tags text[] not null default '{}',
  status text not null default 'operational',
  trust text not null default 'unofficial',
  created_at timestamptz not null default now(),
  last_checked_at timestamptz,
  last_manual_review_at timestamptz,
  response_ms integer,
  failure_reason text,
  consecutive_failures integer not null default 0
);

create table if not exists public.resource_clicks (
  id bigint generated by default as identity primary key,
  resource_id text references public.resources(id) on delete cascade,
  category text,
  referrer text,
  user_agent text,
  country text,
  city text,
  created_at timestamptz not null default now()
);

create or replace view public.resources_with_usage as
select
  r.*,
  count(c.id) filter (where c.created_at >= now() - interval '24 hours')::int as clicks_24h,
  count(c.id) filter (where c.created_at >= now() - interval '7 days')::int as clicks_7d
from public.resources r
left join public.resource_clicks c on c.resource_id = r.id
group by r.id;
